import React, { useState, useEffect, useRef } from 'react';
import moment from 'moment';
import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';

import Header from 'components/ui/header';
import NavBar from 'components/layout/navbar';
import NewBreadCrumb from 'components/ui/breadcrumb';
import Footer from 'components/ui/footer';
import MonthYearPicker from 'components/common/monthYearPicker';
import { byteArrayToBase64, autoGenerateDownloadLink, actionTryCatchCreator, firstDayInPreviousMonth } from 'utils';
import { lapseListingService } from 'services/ehi-gravitrap-audit/upload-adhoc-lapse';
import InPageLoading from 'components/common/inPageLoading';
import { getMastercodeAction } from 'store/actions';
import SearchableCheckList from 'components/common/searchable-check-list';
import CheckForEncryption from 'modules/checkForEncryption';

import { generateAdHocLapsesService } from 'services/report/site-paper-audit';
import { WEB_ROUTES, GRAVITRAP_LAPSE_TYPE, FUNCTION_NAMES } from 'constants/index';

const AdHocLapse = (props) => {
  const [startDate, setStartDate] = useState(firstDayInPreviousMonth(new Date()));
  const [endDate, setEndDate] = useState(new Date());
  const [lapseTypeList, setLapseTypeList] = useState([]);
  const [lapseLOV, setLapseLOV] = useState([]);
  const [isLoading, setLocalLoading] = useState(false);
  const passwordModalRef = useRef(null);

  useEffect(() => {
    document.title = `NEA | ${WEB_ROUTES.REPORT.EHI_ADHOC_LAPSES.name}`;
    getLapseLOVAction();
  }, []);

  const onSearch = (password) => {
    const [fromMonth, fromYear] = moment(startDate).format('MM/YYYY').split('/');
    const [toMonth, toYear] = moment(endDate).format('MM/YYYY').split('/');
    const reportParameters = [
      { name: 'eYearFrom', value: fromYear },
      { name: 'eYearTo', value: toYear },
      { name: 'eMonthFrom', value: fromMonth },
      { name: 'eMonthTo', value: toMonth },
      { name: 'LapseType', value: lapseTypeList[0]?.value || '' },
    ];

    const onPending = () => {
      setLocalLoading(true);
    };
    const onSuccess = (data) => {
      const { extension, mimeType, reportData } = data;
      autoGenerateDownloadLink(`${WEB_ROUTES.REPORT.EHI_ADHOC_LAPSES.name}.${extension}`, mimeType, byteArrayToBase64(reportData));
      setLocalLoading(false);
    };
    const onError = (error) => {
      setLocalLoading(false);
    };
    return actionTryCatchCreator(generateAdHocLapsesService({ reportParameters, password }), onPending, onSuccess, onError);
  };

  const getLapseLOVAction = () => {
    const onPending = () => {
      setLocalLoading(true);
    };
    const onSuccess = (data) => {
      setLocalLoading(false);
      const list = data?.ehiLapseRequestVOList || [];
      const payload = list?.map(({ lapseCode, lapseDescription }) => ({ value: lapseCode, label: lapseDescription })) || [];
      setLapseLOV(payload);
    };
    const onError = () => {
      setLocalLoading(false);
    };
    actionTryCatchCreator(lapseListingService(GRAVITRAP_LAPSE_TYPE.AD_HOC, true), onPending, onSuccess, onError);
  };

  return (
    <>
      <Header />
      <div className="main-content">
        <NavBar active={WEB_ROUTES.REPORT.EHI_ADHOC_LAPSES.name} />
        <div className="contentWrapper">
          <NewBreadCrumb page={[WEB_ROUTES.REPORT, WEB_ROUTES.REPORT.EHI_ADHOC_LAPSES]} />
          <div className="main-title">
            <h1>{WEB_ROUTES.REPORT.EHI_ADHOC_LAPSES.name}</h1>
          </div>
          <div className="paddingLeft30">
            <h2>Selection Criteria</h2>
          </div>
          <div className="block-summary filterMainWrapper tabsContainer" style={{ padding: '30px' }}>
            <div className="tab-pane__group bg-white">
              <div className="card">
                <div className="form-inline mb-4">
                  <div className="mt-2 mr-2 xs-paddingBottom15">
                    <MonthYearPicker
                      label="EYear - EMonth From (*)"
                      selected={startDate}
                      onChange={setStartDate}
                      dateFormat="MMMM, yyyy"
                      maxDate={endDate}
                      minDate={moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years').toDate()}
                    />
                  </div>
                  <div className="mt-2 mr-2">
                    <MonthYearPicker
                      label="EYear - EMonth To (*)"
                      selected={endDate}
                      onChange={setEndDate}
                      dateFormat="MMMM, yyyy"
                      minDate={startDate || moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years').toDate()}
                    />
                  </div>
                </div>

                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="Lapse Type" options={lapseLOV} onChange={(list) => setLapseTypeList(list)} singleChoice />
                  </div>
                </div>
              </div>
            </div>

            <div className="d-flex">
              <button type="submit" className="btn btn-pri" onClick={passwordModalRef?.current?.showPasswordModal}>
                Generate
              </button>
            </div>
          </div>
          <InPageLoading isLoading={isLoading} />
          <Footer />
          <CheckForEncryption functionName={FUNCTION_NAMES.generateAdHocLapses} ref={passwordModalRef} onGenerate={onSearch} />
        </div>
      </div>
    </>
  );
};

const mapStateToProps = ({ global }, ownProps) => ({
  ...ownProps,
  masterCodes: global.data.masterCodes,
});

const mapDispatchToProps = { getMastercodeAction };

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(AdHocLapse));
