import React, { useState, useEffect, useRef } from 'react';

import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import Header from 'components/ui/header';
import NavBar from 'components/layout/navbar';
import NewBreadCrumb from 'components/ui/breadcrumb';
import Footer from 'components/ui/footer';
import { byteArrayToBase64, autoGenerateDownloadLink, actionTryCatchCreator } from 'utils';
import moment from 'moment';
import InPageLoading from 'components/common/inPageLoading';
import { getMastercodeAction, MASTER_CODE } from 'store/actions';
import SearchableCheckList from 'components/common/searchable-check-list';
import MonthYearPicker from 'components/common/monthYearPicker';
import CheckForEncryption from 'modules/checkForEncryption';

import { WEB_ROUTES, FUNCTION_NAMES } from 'constants/index';

import { generateCertificationReportService } from 'services/report/site-paper-audit';

const CertificationReport = (props) => {
  const { getMastercodeAction, masterCodes } = props;
  const [startDate, setStartDate] = useState(moment().toDate());
  const [roList, setROList] = useState([]);
  const [grcList, setGRCList] = useState([]);

  const [isLoading, setLocalLoading] = useState(false);
  const passwordModalRef = useRef(null);

  useEffect(() => {
    document.title = `NEA | ${WEB_ROUTES.REPORT.CERTIFICATION_REPORT.name}`;
    getMastercodeAction([MASTER_CODE.RO_CODE, MASTER_CODE.CDC_CODE], undefined, true);
  }, [getMastercodeAction]);

  const onSearch = (password) => {
    const from = moment(startDate).format('YYYY_MM');
    const reportParameters = [
      { name: 'Year_Month', value: from },
      { name: 'RO', value: roList[0]?.value || '' },
      { name: 'CDC', value: grcList[0]?.value || '' },
    ];

    const onPending = () => {
      setLocalLoading(true);
    };
    const onSuccess = (data) => {
      const { extension, mimeType, reportData } = data;
      autoGenerateDownloadLink(`${WEB_ROUTES.REPORT.CERTIFICATION_REPORT.name}.${extension}`, mimeType, byteArrayToBase64(reportData));
      setLocalLoading(false);
    };
    const onError = (error) => {
      setLocalLoading(false);
    };
    return actionTryCatchCreator(generateCertificationReportService({ reportParameters, password }), onPending, onSuccess, onError);
  };

  const isMandatory = startDate && roList.length > 0 && grcList.length > 0;

  return (
    <>
      <Header />
      <div className="main-content">
        <NavBar active={WEB_ROUTES.REPORT.CERTIFICATION_REPORT.name} />
        <div className="contentWrapper">
          <NewBreadCrumb page={[WEB_ROUTES.REPORT, WEB_ROUTES.REPORT.CERTIFICATION_REPORT]} />
          <div className="main-title">
            <h1>{WEB_ROUTES.REPORT.CERTIFICATION_REPORT.name}</h1>
          </div>
          <div className="paddingLeft30">
            <h2>Selection Criteria</h2>
          </div>
          <div className="block-summary filterMainWrapper tabsContainer" style={{ padding: '30px' }}>
            <div className="tab-pane__group bg-white">
              <div className="card">
                <div className="form-inline marginBottom30">
                  <div className="paddingRight25 xs-paddingBottom15">
                    <MonthYearPicker
                      label="Year - Month (*)"
                      selected={startDate}
                      onChange={setStartDate}
                      dateFormat="MMMM, yyyy"
                      minDate={moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years').toDate()}
                    />
                  </div>
                </div>

                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="RO (*)" options={masterCodes[MASTER_CODE.RO_CODE]} onChange={(list) => setROList(list)} singleChoice />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="CDC (*)" options={masterCodes[MASTER_CODE.CDC_CODE]} onChange={(list) => setGRCList(list)} singleChoice />
                  </div>
                </div>
              </div>
            </div>

            <div className="d-flex">
              <button type="submit" className="btn btn-pri" onClick={passwordModalRef?.current?.showPasswordModal} disabled={!isMandatory}>
                Generate
              </button>
            </div>
          </div>
          <InPageLoading isLoading={isLoading} />
          <Footer />
          <CheckForEncryption functionName={FUNCTION_NAMES.generateCertificationReport} ref={passwordModalRef} onGenerate={onSearch} />
        </div>
      </div>
    </>
  );
};

const mapStateToProps = ({ global }, ownProps) => ({
  ...ownProps,
  masterCodes: global.data.masterCodes,
});

const mapDispatchToProps = { getMastercodeAction };

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(CertificationReport));
