import { downloadUserAuditLogService } from 'services/audit-trails-reports/user-audit-log';
import { actionCreator, actionTryCatchCreator, byteArrayToBase64, autoGenerateDownloadLink } from 'utils';

export const defaultFilterValue = {
  searchText: '',
  searchType: 'userTable',
  datePickerValue: null,
  filterValue: null,
  sortValue: {
    id: 'date',
    label: 'Date',
    desc: false,
    sortType: 'dateTime',
  },
};

export const USER_AUDIT_LOG_DOWNLOAD = actionCreator('USER_AUDIT_LOG_DOWNLOAD');
export const downloadListAction = (params) => async (dispatch) => {
  const onPending = () => {
    dispatch({ type: USER_AUDIT_LOG_DOWNLOAD.PENDING });
  };
  const onSuccess = (data) => {
    dispatch({
      type: USER_AUDIT_LOG_DOWNLOAD.SUCCESS,
      payload: data,
    });
    const base64 = byteArrayToBase64(data?.file || []);
    autoGenerateDownloadLink(`${data?.fileName}.xlsx`, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', base64);
  };
  const onError = (error) => {
    dispatch({ type: USER_AUDIT_LOG_DOWNLOAD.ERROR, payload: error });
  };

  await actionTryCatchCreator(downloadUserAuditLogService(params), onPending, onSuccess, onError);
};
