import React, { useState, useEffect, useRef } from 'react';
import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import moment from 'moment';

import SearchableCheckList from 'components/common/searchable-check-list';
import InPageLoading from 'components/common/inPageLoading';
import Header from 'components/ui/header';
import NavBar from 'components/layout/navbar';
import NewBreadCrumb from 'components/ui/breadcrumb';
import Footer from 'components/ui/footer';
import SingleDatePickerV2 from 'components/common/single-date-picker';
import CheckForEncryption from 'modules/checkForEncryption';

import { dateStringFromDate, byteArrayToBase64, autoGenerateDownloadLink, actionTryCatchCreator } from 'utils';
import { WEB_ROUTES, FUNCTION_NAMES } from 'constants/index';
import { generateDailySpecimenReceivedFromRoService } from 'services/report/sample-identification';
import { getMastercodeAction, MASTER_CODE } from 'store/actions';

const DailySpecimenReceivedFromRO = (props) => {
  const { getMastercodeAction, masterCodes } = props;
  const [startDate, setStartDate] = useState(moment().add(-1, 'days'));
  const [endDate, setEndDate] = useState(moment());
  const [specimenList, setSpecimenList] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const passwordModalRef = useRef(null);

  useEffect(() => {
    document.title = `NEA | ${WEB_ROUTES.REPORT.DAILY_SPECIMEN_RECEIVED_FROM_RO.name}`;
    getMastercodeAction([MASTER_CODE.SPECIMEN_CODE], undefined, true);
  }, [getMastercodeAction]);

  const onSearch = (password) => {
    const reportParameters = [
      { name: 'sampleReceivedStartDate', value: dateStringFromDate(startDate) },
      { name: 'sampleReceivedEndDate', value: dateStringFromDate(endDate) },
      { name: 'Specimen', values: specimenList.map((item) => item?.value || '') },
    ];
    return actionTryCatchCreator(
      generateDailySpecimenReceivedFromRoService({ reportParameters, password }),
      () => setIsLoading(true),
      (data) => {
        setIsLoading(false);
        const { extension, mimeType, reportData } = data;
        autoGenerateDownloadLink(`${WEB_ROUTES.REPORT.DAILY_SPECIMEN_RECEIVED_FROM_RO.name}.${extension}`, mimeType, byteArrayToBase64(reportData));
      },
      () => setIsLoading(false),
    );
  };

  const canGenerate = startDate && endDate;

  return (
    <>
      <Header />
      <div className="main-content">
        <NavBar active={WEB_ROUTES.REPORT.DAILY_SPECIMEN_RECEIVED_FROM_RO.name} />
        <div className="contentWrapper">
          <NewBreadCrumb page={[WEB_ROUTES.REPORT, WEB_ROUTES.REPORT.DAILY_SPECIMEN_RECEIVED_FROM_RO]} />
          <div className="main-title">
            <h1>{WEB_ROUTES.REPORT.DAILY_SPECIMEN_RECEIVED_FROM_RO.name}</h1>
          </div>
          <div className="paddingLeft30">
            <h2>Selection Criteria</h2>
          </div>
          <div className="block-summary filterMainWrapper tabsContainer" style={{ padding: '30px' }}>
            <div className="tab-pane__group bg-white">
              <div className="card">
                <div className="form-inline mb-4">
                  <div>
                    <b className="text-body mr-2">Received Start Date (*)</b>
                    <SingleDatePickerV2
                      className="mt-2 mr-2 xs-paddingBottom15"
                      date={startDate}
                      onChangeDate={setStartDate}
                      minDate={moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years')}
                      maxDate={endDate}
                    />
                  </div>
                  <div>
                    <b className="text-body mr-2">Received End Date (*)</b>
                    <SingleDatePickerV2
                      className="mt-2 mr-2 xs-paddingBottom15"
                      date={endDate}
                      onChangeDate={setEndDate}
                      minDate={startDate || moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years')}
                    />
                  </div>
                </div>
                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="Specimen" options={masterCodes[MASTER_CODE.SPECIMEN_CODE]} onChange={setSpecimenList} />
                  </div>
                </div>
              </div>
            </div>

            <div className="d-flex">
              <button type="submit" className="btn btn-pri" onClick={passwordModalRef?.current?.showPasswordModal} disabled={!canGenerate}>
                Generate
              </button>
            </div>

            <div className="justify-content-center d-flex" />
          </div>
          <InPageLoading isLoading={isLoading} />
          <Footer />
          <CheckForEncryption functionName={FUNCTION_NAMES.generateDailySpecimenReceivedFromRO} ref={passwordModalRef} onGenerate={onSearch} />
        </div>
      </div>
    </>
  );
};

const mapStateToProps = ({ global }, ownProps) => ({
  ...ownProps,
  masterCodes: global.data.masterCodes,
});

const mapDispatchToProps = { getMastercodeAction };

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(DailySpecimenReceivedFromRO));
