import React, { useState, useReducer } from 'react';
import Carousel, { Modal, ModalGateway } from 'react-images';
import Slider from 'react-slick';
import BinaryFile from 'components/common/binaryImage';
import _ from 'lodash';
import { autoGenerateDownloadLink } from 'utils';

const ClickableImageView = (props) => {
  const {
    currentView: {
      src,
      fileName,
      fileType,
      binary,
      // isImage,
    },
  } = props;
  return (
    <div className="react-images__view react-images__view--isModal" style={{ lineHeight: 0, position: 'relative', boxSizing: 'border-box', textAlign: 'center' }}>
      <img className="react-images__view-image--isModal" src={src} alt={fileName} style={{ userSelect: 'none', boxSizing: 'border-box', height: 'auto', maxHeight: '100vh', maxWidth: '100%' }} />
      <p className="text-white cursor-pointer m-2 font-weight-bold pt-3" onClick={() => autoGenerateDownloadLink(fileName, fileType, binary)}>
        Click to download
      </p>
    </div>
  );
};

const BinaryFileSlider = (props) => {
  const { fileList } = props;

  const [carouselState, setCarouselState] = useState({ open: false, index: 0 });

  const [imageSrcs, dispatch] = useReducer(
    (imageSrcs, { type, payload }) => {
      switch (type) {
        case 'update': {
          const temp = _.cloneDeep(imageSrcs);
          temp[payload.index] = payload.value;
          return temp;
        }
        default:
          return imageSrcs;
      }
    },
    (fileList || []).map(() => ({ src: '', isLoaded: false, fileName: 'Loading...' })),
  );

  const onImageLoaded = (file, index) => {
    dispatch({ type: 'update', payload: { index, value: { ...file, isLoaded: true } } });
  };
  return (
    <>
      <Slider dots={false} infinite={false} speed={500} slidesToScroll={1} slidesToShow={1}>
        {fileList.map((file, index) => (
          <div key={`review_reject_image_${index.toString()}`}>
            <BinaryFile fileId={file.fileId} onImageLoaded={(image) => onImageLoaded(image, index)} onClick={() => imageSrcs[index].isLoaded && setCarouselState({ open: true, index })} />
            <p>
              {index + 1}. {file.fileName || imageSrcs[index].fileName}
            </p>
          </div>
        ))}
      </Slider>
      <ModalGateway>
        {carouselState.open ? (
          <Modal
            onClose={() => setCarouselState({ open: false, index: 0 })}
            styles={{
              blanket: (base) => ({ ...base, zIndex: 1100 }),
              positioner: (base) => ({ ...base, zIndex: 1110 }),
              dialog: (base) => ({ ...base, zIndex: 1120 }),
            }}>
            <Carousel views={imageSrcs} currentIndex={carouselState.index} components={{ View: ClickableImageView }} />
          </Modal>
        ) : null}
      </ModalGateway>
    </>
  );
};

export default BinaryFileSlider;
