import React, { useState, useEffect, useRef } from 'react';

import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import Header from 'components/ui/header';
import NavBar from 'components/layout/navbar';
import NewBreadCrumb from 'components/ui/breadcrumb';
import Footer from 'components/ui/footer';
import SingleDatePickerV2 from 'components/common/single-date-picker';
import { dateStringFromDate, byteArrayToBase64, autoGenerateDownloadLink, actionTryCatchCreator } from 'utils';
import moment from 'moment';
import InPageLoading from 'components/common/inPageLoading';
import { getMastercodeAction, MASTER_CODE } from 'store/actions';
import Select from 'components/common/select';
import SearchableCheckList from 'components/common/searchable-check-list';
import CheckForEncryption from 'modules/checkForEncryption';

import { generateSurveyByRoadReportService } from 'services/report/inspection-management';
import { getUserRolesLovService } from 'services/non-functional';
import { WEB_ROUTES, FUNCTION_NAMES } from 'constants/index';

const SurveyByRoadReport = (props) => {
  const { getMastercodeAction, masterCodes } = props;
  const [startDate, setStartDate] = useState(moment().add(-1, 'days'));
  const [endDate, setEndDate] = useState(moment());
  const [surveyor, setSurveyor] = useState();
  const [road, setRoad] = useState('');
  const [roList, setROList] = useState([]);
  const [grcList, setGRCList] = useState([]);
  const [divisionList, setDivisionList] = useState([]);
  const [vectorTypeList, setVectorTypeList] = useState([]);

  const [surveyLOV, setSurveyLOV] = useState([]);
  const [isLoading, setLocalLoading] = useState(false);
  const passwordModalRef = useRef(null);

  const getSurveyorLOV = () => {
    const onPending = () => {
      setLocalLoading(true);
    };
    const onSuccess = (data) => {
      const lov = (data?.rolesWithUsersVOList[0]?.anaUserVOList || []).map((role) => ({
        label: role.fullName,
        value: role.soeId,
      }));
      setSurveyLOV(lov);
      setLocalLoading(false);
    };
    const onError = (error) => {
      setLocalLoading(false);
    };
    actionTryCatchCreator(getUserRolesLovService({ roles: ['ROOfficer'] }), onPending, onSuccess, onError);
  };

  useEffect(() => {
    getSurveyorLOV();
  }, []);

  useEffect(() => {
    document.title = `NEA | ${WEB_ROUTES.REPORT.SURVEY_BY_ROAD.name}`;
    getMastercodeAction([MASTER_CODE.RO_CODE, MASTER_CODE.GRC_CODE, MASTER_CODE.DIVISION_CODE, MASTER_CODE.SPECIMEN_CODE], undefined, true);
  }, [getMastercodeAction]);

  const onSearch = (password) => {
    const reportParameters = [
      { name: 'surveyDateFrom', value: dateStringFromDate(startDate) },
      { name: 'surveyDateTo', value: dateStringFromDate(endDate) },
      { name: 'Surveyor', value: surveyor?.value || '' },
      { name: 'Road', value: road },
      { name: 'VectorType', value: vectorTypeList[0]?.value },
      { name: 'RO', values: roList.map((item) => item?.value || '') },
      { name: 'GRC', values: grcList.map((item) => item?.value || '') },
      { name: 'Division', values: divisionList.map((item) => item?.value || '') },
    ];

    const onPending = () => {
      setLocalLoading(true);
    };
    const onSuccess = (data) => {
      const { extension, mimeType, reportData } = data;
      autoGenerateDownloadLink(`${WEB_ROUTES.REPORT.SURVEY_BY_ROAD.name}.${extension}`, mimeType, byteArrayToBase64(reportData));
      setLocalLoading(false);
    };
    const onError = () => {
      setLocalLoading(false);
    };
    return actionTryCatchCreator(generateSurveyByRoadReportService({ reportParameters, password }), onPending, onSuccess, onError);
  };

  const isMandatory = startDate && endDate && surveyor && road && vectorTypeList.length > 0 && roList.length > 0 && grcList.length > 0 && divisionList.length > 0;

  return (
    <>
      <Header />
      <div className="main-content">
        <NavBar active={WEB_ROUTES.REPORT.SURVEY_BY_ROAD.name} />
        <div className="contentWrapper">
          <NewBreadCrumb page={[WEB_ROUTES.REPORT, WEB_ROUTES.REPORT.SURVEY_BY_ROAD]} />
          <div className="main-title">
            <h1>{WEB_ROUTES.REPORT.SURVEY_BY_ROAD.name}</h1>
          </div>
          <div className="paddingLeft30">
            <h2>Selection Criteria</h2>
          </div>
          <div className="block-summary filterMainWrapper tabsContainer" style={{ padding: '30px' }}>
            <div className="tab-pane__group bg-white">
              <div className="card">
                <div className="form-inline mb-4">
                  <div>
                    <b className="text-body">Survey Date From (*)</b>
                    <SingleDatePickerV2
                      className="mt-2 mr-2 xs-paddingBottom15"
                      date={startDate}
                      onChangeDate={setStartDate}
                      minDate={moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years')}
                      maxDate={endDate}
                    />
                  </div>
                  <div>
                    <b className="text-body">Survey Date To (*)</b>
                    <SingleDatePickerV2
                      className="mt-2 mr-2 xs-paddingBottom15"
                      date={endDate}
                      onChangeDate={setEndDate}
                      minDate={startDate || moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years')}
                    />
                  </div>
                </div>
                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked mb-4">
                    <b className="text-body">Surveyor (*)</b>
                    <Select className="m-1 w-100 d-block" options={surveyLOV} value={surveyor} onChange={setSurveyor} />
                  </div>
                </div>
                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked flex-column">
                    <b className="text-body">Road (*)</b>
                    <input
                      className="textfield"
                      onChange={(event) => {
                        setRoad(event.target.value);
                      }}
                    />
                  </div>
                </div>

                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="Vector Type (*)" options={masterCodes[MASTER_CODE.SPECIMEN_CODE]} onChange={(list) => setVectorTypeList(list)} singleChoice placeholder="Mandatory" />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="RO (*)" options={masterCodes[MASTER_CODE.RO_CODE]} onChange={(list) => setROList(list)} placeholder="Mandatory" />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="GRC (*)" options={masterCodes[MASTER_CODE.GRC_CODE]} onChange={(list) => setGRCList(list)} placeholder="Mandatory" />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="Division (*)" options={masterCodes[MASTER_CODE.DIVISION_CODE]} onChange={(list) => setDivisionList(list)} placeholder="Mandatory" />
                  </div>
                </div>
              </div>
            </div>

            <div className="d-flex">
              <button type="submit" className="btn btn-pri" onClick={passwordModalRef?.current?.showPasswordModal} disabled={!isMandatory}>
                Generate
              </button>
            </div>
          </div>
          <InPageLoading isLoading={isLoading} />
          <Footer />
          <CheckForEncryption functionName={FUNCTION_NAMES.generateSurveyByRoad} ref={passwordModalRef} onGenerate={onSearch} />
        </div>
      </div>
    </>
  );
};

const mapStateToProps = ({ global }, ownProps) => ({
  ...ownProps,
  masterCodes: global.data.masterCodes,
});

const mapDispatchToProps = { getMastercodeAction };

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(SurveyByRoadReport));
