const MASTER_CODE = {
  SPECIMEN_CODE: 'VCS_SPM_CD', // !
  SPECIES_CODE: 'VCS_SPE_CD',
  DIVISION_CODE: 'VCS_DIV_CD', // !
  RO_CODE: 'VCS_RO_CD', // !
  CDC_CODE: 'VCS_CDC_CD', // !
  TC_CODE: 'VCS_TC_CD', // !
  GRC_CODE: 'VCS_GRC_CD', // !
  CONTACT_MODE_DURING_ATTEMPS: 'VCS_ATM_MD', // !
  CONTACT_OUTCOME_DURING_ATTEMPS: 'VCS_ATM_OC', // !
  RELATION: 'VCS_ATM_RL', // !
  INSPECTION_PURPOSE: 'VCS_INS_PP', // !
  INSPECTION_STATUS: 'VCS_INS_ST', // !
  INSPECTION_TYPE: 'VCS_INS_TY', // !
  HABITAT_CODE: 'VCS_HAB_CD', // !
  HABITAT_SIZE_UNIT: 'VCS_HAB_SU', // !
  LOCATION_OF_BREEDING: 'VCS_LOC_BR', // !
  SPECIMEN_RODENT_TYPE: 'VCS_SPM_TP', // !
  SAMPLE_TREATMENT: 'VCS_SMP_TM', // !
  FINDING_REASON: 'VCS_FND_RS', // !
  FINDING_STATUS: 'VCS_FND_ST', // !
  PREMISES_TYPE: 'VCS_PRE_TY', // !
  FOGGING_AUDIT_TASK_STATUS: 'VCS_FAT_ST', // !
  FOGGING_PURPOSE: 'VCS_FOG_PP', // !
  APPLICATION_MODE: 'VCS_MOD_AP', // !
  FOGGING_AUDIT_ITEMS: 'VCS_FOA_IT', // !
  CASE_TYPE: 'VCS_DSE_TP', // !
  ID_TYPE: 'VCS_ID_TP', // !
  SAMPLE_TREATMENT_PURPOSE: 'VCS_SMP_TP', // !
  ETHNIC_TYPE: 'VCS_ETH_CD', // !
  OCCUPATION_TYPE: 'VCS_OCC_CD', // !
  EPI_STATUS: 'VCS_EPI_ST', // !
  COUNTRY: 'VCS_CTR_CD', // !
  RESIDENTIAL_TYPE: 'VCS_RSD_ST', // !
  GENDER: 'VCS_SEX_CD', // !
  WORK_HOUR_TYPE: 'VCS_WRK_TY', // !
  CLINIC_TYPE: 'VCS_CLN_TY', // !
  RECOMMENDATION_ON_CASE_STATUS: 'VCS_REC_ST', // !
  SYMPTOMS: 'VCS_SYM_CD', // !
  ACCESSIBILITY: 'VCS_ACC_CD', // !
  INSPECTION_FORM_STATUS: 'VCS_IPF_ST', // !
  WITNESS_RELATIONSHIP: 'VCS_WIT_RE', // !
  SAMPLE_FINDING_RESEARCH_PURPOSE: 'VCS_FND_PP', // !
  SPECIMEN_STAGE: 'VCS_SPM_ST', // !
  PREVENTIVE_MEASURE: 'VCS_PRE_MS', // !
  ADDITIONAL_INFO: 'VCS_ADD_IF', // !
  SAMPLE_REJECT_REASONS: 'VCS_REJ_ST', // !
  SALUTATION: 'VCS_OFF_SL',
  LOI_TYPE: 'VCS_LOI_TY',
  INSERT_NOTICE_REASON: 'VCS_NOT_IR',
  DISEASE_TYPE: 'VCS_DIS_CD',
  HQ_REPORT_LOV_SPE: 'LOV_SPE',
  HQ_REPORT_LOV_SPE_SPM: 'LOV_SPE_SPM',
  NOTIFICATION_TEMPLATE_TYPE: 'VCS_NOT_TP',
  ASSIGNED_GROUP: 'VCS_ASS_GP',
  TRANSPORT_MODE: 'VCS_TRP_M',
  BUS_STOP: 'VCS_BUS_ST',
  MRT_STOP: 'VCS_MRT_ST',
  GROUP_BY: 'VCS_GRP_BY',
  GRAVITRAP_AUDIT_SPECIMEN: 'VCS_GTA_SP',
  INITIAL_LAPSE: 'VCS_INI_LP',
  FINAL_LAPSE: 'VCS_FIN_LP',
  OFFENDER_ID_TYPE: 'VCS_OFF_TY',
  SITE_PAPER_LAPSES_OBSERVED: 'VCS_SP_LP',
  LAPSE_TYPE: 'VCS_GRV_LP',
  SAMPLE_STATUS_CODE: 'VCS_SMP_ST',
  PERSONAL_CONTACT: 'VCS_PC_CD',
  EPI_DISEASE_TYPE: 'VCS_EPI_TY',
  EHI_FINDING_TYPE: 'VCS_SP_FT',
  SITE_PAPER_FILE_TYPE: 'VCS_SP_AF',
  EPI_CDC_COB: 'VCS_CD_COB',
  DASHBOARD_WIDGET: 'VCS_DB_W',
};

export default MASTER_CODE;
