import React, { useState, useEffect, useRef } from 'react';

import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import Header from 'components/ui/header';
import NavBar from 'components/layout/navbar';
import NewBreadCrumb from 'components/ui/breadcrumb';
import Footer from 'components/ui/footer';
import { byteArrayToBase64, autoGenerateDownloadLink, actionTryCatchCreator } from 'utils';
import InPageLoading from 'components/common/inPageLoading';
import { getMastercodeAction, MASTER_CODE } from 'store/actions';
import SearchableCheckList from 'components/common/searchable-check-list';
import CheckForEncryption from 'modules/checkForEncryption';

import { generateEPIClusterSummaryService } from 'services/report/epi';
import { WEB_ROUTES, FUNCTION_NAMES } from 'constants/index';

const ClusterSummaryReport = (props) => {
  const { getMastercodeAction, masterCodes } = props;

  const [clusterId, setClusterId] = useState('');
  const [cdcList, setCDCList] = useState([]);
  const [divisionList, setDivisionList] = useState([]);

  const [isLoading, setLocalLoading] = useState(false);
  const passwordModalRef = useRef(null);

  useEffect(() => {
    document.title = `NEA | ${WEB_ROUTES.REPORT.CLUSTER_SUMMARY_REPORT.name}`;
    getMastercodeAction([MASTER_CODE.CDC_CODE, MASTER_CODE.DIVISION_CODE], undefined, true);
  }, [getMastercodeAction]);

  const onSearch = async (password) => {
    const reportParameters = [
      { name: 'clusterId', value: clusterId },
      { name: 'CDC', values: cdcList.map((item) => item?.value || '') },
      { name: 'Division', values: divisionList.map((item) => item?.value || '') },
    ];

    const onPending = () => setLocalLoading(true);
    const onSuccess = (data) => {
      const { extension, mimeType, reportData } = data;
      autoGenerateDownloadLink(`${WEB_ROUTES.REPORT.CLUSTER_SUMMARY_REPORT.name}.${extension}`, mimeType, byteArrayToBase64(reportData));
      setLocalLoading(false);
    };
    const onError = () => {
      setLocalLoading(false);
    };
    return actionTryCatchCreator(generateEPIClusterSummaryService({ reportParameters, password }), onPending, onSuccess, onError);
  };

  return (
    <>
      <Header />
      <div className="main-content">
        <NavBar active={WEB_ROUTES.REPORT.CLUSTER_SUMMARY_REPORT.name} />
        <div className="contentWrapper">
          <NewBreadCrumb page={[WEB_ROUTES.REPORT, WEB_ROUTES.REPORT.CLUSTER_SUMMARY_REPORT]} />
          <div className="main-title">
            <h1>{WEB_ROUTES.REPORT.CLUSTER_SUMMARY_REPORT.name}</h1>
          </div>
          <div className="paddingLeft30">
            <h2>Selection Criteria</h2>
          </div>
          <div className="block-summary filterMainWrapper tabsContainer" style={{ padding: '30px' }}>
            <div className="tab-pane__group bg-white">
              <div className="card">
                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked flex-column">
                    <b className="text-body">Cluster ID</b>
                    <input className="textfield" onChange={(e) => setClusterId(e.target.value)} />
                  </div>
                </div>

                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="CDC" options={masterCodes[MASTER_CODE.CDC_CODE]} onChange={setCDCList} />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="Division" options={masterCodes[MASTER_CODE.DIVISION_CODE]} onChange={setDivisionList} />
                  </div>
                </div>
              </div>
            </div>

            <div className="d-flex">
              <button type="submit" className="btn btn-pri" onClick={passwordModalRef?.current?.showPasswordModal}>
                Generate
              </button>
            </div>
          </div>
          <InPageLoading isLoading={isLoading} />
          <Footer />
          <CheckForEncryption functionName={FUNCTION_NAMES.generateEPIClusterSummary} ref={passwordModalRef} onGenerate={onSearch} />
        </div>
      </div>
    </>
  );
};

const mapStateToProps = ({ global }, ownProps) => ({
  ...ownProps,
  masterCodes: global.data.masterCodes,
});

const mapDispatchToProps = { getMastercodeAction };

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(ClusterSummaryReport));
