import React, { useState, useEffect, useRef } from 'react';

import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import Header from 'components/ui/header';
import NavBar from 'components/layout/navbar';
import NewBreadCrumb from 'components/ui/breadcrumb';
import Footer from 'components/ui/footer';
import MonthYearPicker from 'components/common/monthYearPicker';
import { byteArrayToBase64, autoGenerateDownloadLink, actionTryCatchCreator, firstDayInPreviousMonth } from 'utils';
import moment from 'moment';
import InPageLoading from 'components/common/inPageLoading';
import { getMastercodeAction, MASTER_CODE } from 'store/actions';
import SearchableCheckList from 'components/common/searchable-check-list';
import CheckForEncryption from 'modules/checkForEncryption';

import { generateBreedingInspectionEmonthReportService } from 'services/report/hq';
import { WEB_ROUTES, FUNCTION_NAMES } from 'constants/index';

const HQBreedingMasterListInspectionEmonth = (props) => {
  const { getMastercodeAction, masterCodes } = props;
  const [startDate, setStartDate] = useState(firstDayInPreviousMonth(new Date()));
  const [endDate, setEndDate] = useState(new Date());
  const [roList, setROList] = useState([]);
  const [cdcList, setCDCList] = useState([]);
  const [grcList, setGRCList] = useState([]);
  const [divisionList, setDivisionList] = useState([]);
  const [accessibilityList, setAccessibilityList] = useState([]);

  const [isLoading, setLocalLoading] = useState(false);
  const passwordModalRef = useRef(null);

  useEffect(() => {
    document.title = `NEA | ${WEB_ROUTES.REPORT.AEDES_BREEDING_MASTER_LIST_INSPECTIONS_EMONTH.name}`;
    getMastercodeAction([MASTER_CODE.RO_CODE, MASTER_CODE.CDC_CODE, MASTER_CODE.GRC_CODE, MASTER_CODE.DIVISION_CODE, MASTER_CODE.ACCESSIBILITY], undefined, true);
  }, [getMastercodeAction]);

  const onSearch = (password) => {
    const [fromMonth, fromYear] = moment(startDate).format('MM/YYYY').split('/');
    const [toMonth, toYear] = moment(endDate).format('MM/YYYY').split('/');
    const reportParameters = [
      { name: 'eYear_eMonthFrom', value: `${fromYear}_${fromMonth}` },
      { name: 'eYear_eMonthTo', value: `${toYear}_${toMonth}` },
      { name: 'RO', values: roList.map((item) => item?.value || '') },
      { name: 'CDC', values: cdcList.map((item) => item?.value || '') },
      { name: 'GRC', values: grcList.map((item) => item?.value || '') },
      { name: 'Division', values: divisionList.map((item) => item?.value || '') },
      { name: 'Accessibility', values: accessibilityList.map((item) => item?.value || '') },
    ];

    const onPending = () => {
      setLocalLoading(true);
    };
    const onSuccess = (data) => {
      const { extension, mimeType, reportData } = data;
      autoGenerateDownloadLink(`${WEB_ROUTES.REPORT.AEDES_BREEDING_MASTER_LIST_INSPECTIONS_EMONTH.name}.${extension}`, mimeType, byteArrayToBase64(reportData));
      setLocalLoading(false);
    };
    const onError = () => {
      setLocalLoading(false);
    };
    return actionTryCatchCreator(generateBreedingInspectionEmonthReportService({ reportParameters, password }), onPending, onSuccess, onError);
  };

  return (
    <>
      <Header />
      <div className="main-content">
        <NavBar active={WEB_ROUTES.REPORT.AEDES_BREEDING_MASTER_LIST_INSPECTIONS_EMONTH.name} />
        <div className="contentWrapper">
          <NewBreadCrumb page={[WEB_ROUTES.REPORT, WEB_ROUTES.REPORT.AEDES_BREEDING_MASTER_LIST_INSPECTIONS_EMONTH]} />
          <div className="main-title">
            <h1>{WEB_ROUTES.REPORT.AEDES_BREEDING_MASTER_LIST_INSPECTIONS_EMONTH.name}</h1>
          </div>
          <div className="paddingLeft30">
            <h2>Selection Criteria</h2>
          </div>
          <div className="block-summary filterMainWrapper tabsContainer" style={{ padding: '30px' }}>
            <div className="tab-pane__group bg-white">
              <div className="card">
                <div className="form-inline mb-4">
                  <div className="mt-2 mr-2 xs-paddingBottom15">
                    <MonthYearPicker
                      label="EYear - EMonth From (*)"
                      selected={startDate}
                      onChange={setStartDate}
                      dateFormat="MMMM, yyyy"
                      maxDate={endDate}
                      minDate={moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years').toDate()}
                    />
                  </div>
                  <div className="mt-2 mr-2">
                    <MonthYearPicker
                      label="EYear - EMonth To (*)"
                      selected={endDate}
                      onChange={setEndDate}
                      dateFormat="MMMM, yyyy"
                      minDate={startDate || moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years').toDate()}
                    />
                  </div>
                </div>

                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="RO" options={masterCodes[MASTER_CODE.RO_CODE]} onChange={(list) => setROList(list)} />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="CDC" options={masterCodes[MASTER_CODE.CDC_CODE]} onChange={(list) => setCDCList(list)} />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="GRC" options={masterCodes[MASTER_CODE.GRC_CODE]} onChange={(list) => setGRCList(list)} />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="Division" options={masterCodes[MASTER_CODE.DIVISION_CODE]} onChange={(list) => setDivisionList(list)} />
                  </div>
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="Accessibility" options={masterCodes[MASTER_CODE.ACCESSIBILITY]} onChange={(list) => setAccessibilityList(list)} />
                  </div>
                </div>
              </div>
            </div>

            <div className="d-flex">
              <button type="submit" className="btn btn-pri" onClick={passwordModalRef?.current?.showPasswordModal}>
                Generate
              </button>
            </div>
          </div>
          <InPageLoading isLoading={isLoading} />
          <Footer />
          <CheckForEncryption functionName={FUNCTION_NAMES.generateABMLemonthInspections} ref={passwordModalRef} onGenerate={onSearch} />
        </div>
      </div>
    </>
  );
};

const mapStateToProps = ({ global }, ownProps) => ({
  ...ownProps,
  masterCodes: global.data.masterCodes,
});

const mapDispatchToProps = { getMastercodeAction };

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(HQBreedingMasterListInspectionEmonth));
