import React, { useEffect, useState, useRef } from 'react';
import { connect } from 'react-redux';
import { withRouter } from 'react-router-dom';
import { useDebounce } from 'use-debounce';
import { toast } from 'react-toastify';

import Header from 'components/ui/header';
import NavBar from 'components/layout/navbar';
import Footer from 'components/ui/footer';
import NewBreadCrumb from 'components/ui/breadcrumb';
import Sort from 'components/common/sort';
import SearchBox from 'components/common/searchBox';
import DataTable from 'components/common/data-table';
import Filter, { FilterType } from 'components/common/filter';
import InPageLoading from 'components/common/inPageLoading';

import FileTemplates from 'modules/non-functional/file-templates';

import { getFilterArrayOfListForKey, byteArrayToBase64, autoGenerateDownloadLink } from 'utils';

import { downloadFile, downloadUploadedErrorFilesService } from 'services/file-operation';

import { tableColumnWidth, WEB_ROUTES } from 'constants/index';

import { filterListAction, getListAction, defaultFilterValue } from './action';

const UploadedFiles = (props) => {
  const {
    getListAction,
    filterListAction,
    // userRole,

    // history,
    ui: { isLoading },
    data: { filteredList, list },
  } = props;

  const [sortValue, setSortValue] = useState(defaultFilterValue.sortValue);
  const [searchType, setSearchTypeValue] = useState(defaultFilterValue.searchType);
  const [searchText, setSearchTextValue] = useState(defaultFilterValue.searchText);
  const [filterValue, setFilterValue] = useState(defaultFilterValue.filterValue);
  const filterRef = useRef(null);

  const [debounceSearchText] = useDebounce(searchText, 1000);

  useEffect(() => {
    document.title = 'NEA | File Download';
    getListAction().then(() => {
      if (filterRef && filterRef.current) filterRef.current.onClear();
    });
  }, [getListAction]);

  useEffect(() => {
    filterListAction({
      sortValue,
      searchType,
      searchText: debounceSearchText,
      filterValue,
    });
  }, [debounceSearchText, searchType, sortValue, filterValue, filterListAction]);

  const filterData = [
    {
      type: FilterType.SELECT,
      id: 'fileType',
      title: 'File Type',
      values: getFilterArrayOfListForKey(list, 'fileType'),
    },
    {
      type: FilterType.SELECT,
      id: 'fileStatus',
      title: 'File Status',
      values: getFilterArrayOfListForKey(list, 'fileStatus'),
    },
  ];

  const searchData = [
    {
      label: 'File Name',
      value: 'fileName',
    },
  ];

  const downloadNormalFile = async (fileId) => {
    const downloadRequest = downloadFile({ fileId });
    const { status, data } = await downloadRequest.request;
    if (status === 200 && data.status === 'Pass') {
      const base64 = byteArrayToBase64(data.fileData);
      autoGenerateDownloadLink(data.fileName, data.fileType, base64);
    } else {
      toast.error(`Unable to load this file (ID: ${fileId}) : ${data.errorMessage}`);
    }
  };

  const downloadErrorFile = async (fileId) => {
    const downloadRequest = downloadUploadedErrorFilesService({ fileId });
    const { status, data } = await downloadRequest.request;
    if (status === 200 && data.status === 'Pass') {
      const base64 = byteArrayToBase64(data.fileData);
      autoGenerateDownloadLink(data.fileName, data.fileType, base64);
    } else {
      toast.error(`Unable to load this file (ID: ${fileId}) : ${data.errorMessage}`);
    }
  };

  const columns = [
    {
      Header: 'File Name',
      accessor: 'fileName',
      minWidth: tableColumnWidth.xxl,
    },
    {
      Header: 'Submission Type',
      accessor: 'submissionType',
      minWidth: tableColumnWidth.md,
    },
    {
      Header: 'File Type',
      accessor: 'fileType',
      minWidth: tableColumnWidth.md,
    },
    {
      Header: 'Uploaded Date',
      accessor: 'uploadedDate',
      minWidth: tableColumnWidth.lg,
      sortHeader: 'Uploaded Date & Time',
      sortAccessor: 'uploaded',
      combineDateTime: true,
    },
    {
      Header: 'Uploaded Time',
      accessor: 'uploadedTime',
      minWidth: tableColumnWidth.lg,
      hideInSort: true,
    },
    {
      Header: 'File Status',
      accessor: 'fileStatus',
      minWidth: tableColumnWidth.md,
    },
    {
      Header: 'File',
      accessor: 'downloadFile',
      minWidth: tableColumnWidth.lg,
      Cell: (cellInfo) => (
        <button type="button" className="btn btn-sec" onClick={() => downloadNormalFile(cellInfo.row._original.fileId)}>
          Download
        </button>
      ),
    },
    {
      Header: 'Error File',
      accessor: 'downloadErrorFile',
      minWidth: tableColumnWidth.lg,
      Cell: (cellInfo) => {
        if (cellInfo.row._original.errorFile) {
          return (
            <button type="button" className="btn btn-sec" onClick={() => downloadErrorFile(cellInfo.row._original.fileId)}>
              Download
            </button>
          );
        }
        return <></>;
      },
    },
  ];

  return (
    <>
      <Header />
      <div className="main-content workspace__main">
        <NavBar active="File Download" />
        <div className="contentWrapper">
          <NewBreadCrumb page={[WEB_ROUTES.NON_FUNCTIONAL.UPLOADED_FILES]} />
          <div className="main-title">
            <h1>File Download</h1>
            <div className="ml-auto">
              <FileTemplates />
            </div>
          </div>
          <div className="navbar navbar-expand filterMainWrapper">
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <SearchBox name="barcode" placeholder="Enter keywords" onChangeText={setSearchTextValue} searchTypes={searchData} value={searchText} onChangeSearchType={setSearchTypeValue} />
              <Filter ref={filterRef} className="navbar-nav filterWrapper ml-auto xs-paddingBottom15" onChange={setFilterValue} data={filterData} />
              <Sort className="navbar-nav sortWrapper" data={columns.slice(0, columns.length - 2)} value={sortValue} desc={sortValue.desc} onChange={setSortValue} />
            </div>
          </div>
          <div className="tabsContainer">
            <DataTable data={filteredList} columns={columns} />
          </div>
          <InPageLoading isLoading={isLoading} />
          <Footer />
        </div>
      </div>
    </>
  );
};

const mapStateToProps = ({ global, nonFunctionalReducers: { uploadedFiles } }, ownProps) => ({
  ...ownProps,
  ...uploadedFiles,
  userRole: global.ui.userRole,
});

const mapDispatchToProps = {
  filterListAction,
  getListAction,
};

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(UploadedFiles));
