import React, { useState, useEffect, useRef } from 'react';

import { withRouter } from 'react-router-dom';
import { connect } from 'react-redux';
import Header from 'components/ui/header';
import NavBar from 'components/layout/navbar';
import NewBreadCrumb from 'components/ui/breadcrumb';
import Footer from 'components/ui/footer';
import SingleDatePickerV2 from 'components/common/single-date-picker';
import { dateStringFromDate, byteArrayToBase64, autoGenerateDownloadLink, actionTryCatchCreator } from 'utils';
import moment from 'moment';
import InPageLoading from 'components/common/inPageLoading';
import { getMastercodeAction, MASTER_CODE } from 'store/actions';
import SearchableCheckList from 'components/common/searchable-check-list';
import CheckForEncryption from 'modules/checkForEncryption';

import { generateQueryVoidInspectionReportService } from 'services/report/inspection-management';
import { WEB_ROUTES, FUNCTION_NAMES } from 'constants/index';

const QueryVoidInspectionReport = (props) => {
  const { getMastercodeAction, masterCodes } = props;
  const [startDate, setStartDate] = useState(moment().add(-1, 'days'));
  const [endDate, setEndDate] = useState(moment());
  const [roList, setROList] = useState([]);
  const [breeding, setBreeding] = useState(true);

  const [isLoading, setLocalLoading] = useState(false);
  const passwordModalRef = useRef(null);

  useEffect(() => {
    document.title = `NEA | ${WEB_ROUTES.REPORT.QUERY_VOID_INSPECTION.name}`;
    getMastercodeAction([MASTER_CODE.RO_CODE], undefined, true);
  }, [getMastercodeAction]);

  const onSearch = (password) => {
    const reportParameters = [
      { name: 'surveyDateFrom', value: dateStringFromDate(startDate) },
      { name: 'surveyDateTo', value: dateStringFromDate(endDate) },
      { name: 'RO', values: roList.map((item) => item?.value || '') },
      { name: 'Breeding', value: breeding ? 'YES' : 'NO' },
    ];

    const onPending = () => {
      setLocalLoading(true);
    };
    const onSuccess = (data) => {
      const { extension, mimeType, reportData } = data;
      autoGenerateDownloadLink(`${WEB_ROUTES.REPORT.QUERY_VOID_INSPECTION.name}.${extension}`, mimeType, byteArrayToBase64(reportData));
      setLocalLoading(false);
    };
    const onError = (error) => {
      setLocalLoading(false);
    };
    return actionTryCatchCreator(generateQueryVoidInspectionReportService({ reportParameters, password }), onPending, onSuccess, onError);
  };

  const checkMandatory = startDate && endDate && roList.length > 0 && breeding != null;

  return (
    <>
      <Header />
      <div className="main-content">
        <NavBar active={WEB_ROUTES.REPORT.QUERY_VOID_INSPECTION.name} />
        <div className="contentWrapper">
          <NewBreadCrumb page={[WEB_ROUTES.REPORT, WEB_ROUTES.REPORT.QUERY_VOID_INSPECTION]} />
          <div className="main-title">
            <h1>{WEB_ROUTES.REPORT.QUERY_VOID_INSPECTION.name}</h1>
          </div>
          <div className="paddingLeft30">
            <h2>Selection Criteria</h2>
          </div>
          <div className="block-summary filterMainWrapper tabsContainer" style={{ padding: '30px' }}>
            <div className="tab-pane__group bg-white">
              <div className="card">
                <div className="form-inline mb-4">
                  <div>
                    <b className="text-body">Survey Date From (*)</b>
                    <SingleDatePickerV2
                      className="mt-2 mr-2 xs-paddingBottom15"
                      date={startDate}
                      onChangeDate={setStartDate}
                      minDate={moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years')}
                      maxDate={endDate}
                    />
                  </div>
                  <div>
                    <b className="text-body">Survey Date To (*)</b>
                    <SingleDatePickerV2
                      className="mt-2 mr-2 xs-paddingBottom15"
                      date={endDate}
                      onChangeDate={setEndDate}
                      minDate={startDate || moment().add(-process.env.REACT_APP_REPORT_PAST_YEAR, 'years')}
                    />
                  </div>
                </div>
                <div className="form-inline mb-4">
                  <div className="form-group form-group__stacked mb-4">
                    <SearchableCheckList title="RO (*)" options={masterCodes[MASTER_CODE.RO_CODE]} onChange={(list) => setROList(list)} placeholder="Mandatory" />
                  </div>
                </div>

                <div className="form-inline mb-4">
                  <div>
                    <b className="text-body">Breeding (*)</b>
                    <div className="custom-radio mt-2 mr-2">
                      <input type="radio" id="breeding_yes" name="breeding" className="form-input" checked={breeding} onClick={() => setBreeding(true)} />
                      <label className="form-label" htmlFor="breeding_yes">
                        Yes
                      </label>
                    </div>
                    <div className="custom-radio mt-2 mr-2">
                      <input type="radio" id="breeding_no" name="breeding" className="form-input" checked={!breeding} onClick={() => setBreeding(false)} />
                      <label className="form-label" htmlFor="breeding_no">
                        No
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="d-flex">
              <button type="submit" className="btn btn-pri" onClick={passwordModalRef?.current?.showPasswordModal} disabled={!checkMandatory}>
                Generate
              </button>
            </div>
          </div>
          <InPageLoading isLoading={isLoading} />
          <Footer />
          <CheckForEncryption functionName={FUNCTION_NAMES.generateQueryVoidInspection} ref={passwordModalRef} onGenerate={onSearch} />
        </div>
      </div>
    </>
  );
};

const mapStateToProps = ({ global }, ownProps) => ({
  ...ownProps,
  masterCodes: global.data.masterCodes,
});

const mapDispatchToProps = { getMastercodeAction };

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(QueryVoidInspectionReport));
